### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vigneshchalapathy** [RhinoSecurityLabs/IPRotate_Burp_Extension#25]
Traceback (most recent call last):
  File "C:\Users\vigne\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\IPRotate.py", line 202, in enableGateway
    self.startAPIGateway()
  File "C:\Users\vigne\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\IPRotate.py", line 76, in startAPIGateway
    self.create_api_response = self.awsclient.create_rest_api(
  File "C:\Users\vigne\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\vigne\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncompleteSignatureException) when calling the CreateRestApi operation: 'AKIA6BUPO/20200610/eu-west-3/apigateway/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential= AKIA6BUPOJPYK/20200610/eu-west-3/apigateway/aws4_request, SignedHeaders=accept;host;x-amz-date, Signature=7c4264fdf478c733cd41884a62cf0bba98f4730b65e88af6'.

i get this error

i have setup the access keys and secret key .when i gave enable,the above error showsup

**Comment by DaveYesland** [comment]
>AWS4-HMAC-SHA256 Credential=` `AKIA6BUPOJPYK/20200610/eu-west-3/apigateway/aws4_request

Looks like you have leading a space in your keys from copy and pasting.
