### ISSUE TITLE
Cannot enable the enable button

### ISSUE THREAD

**Issue by anandu251** [RhinoSecurityLabs/IPRotate_Burp_Extension#27]
Hey, when I try to click on the enable button, it just hangs for a while and remain disabled. The following error is shown:
Traceback (most recent call last):
  File "/root/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 202, in enableGateway
    self.startAPIGateway()
  File "/root/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 76, in startAPIGateway
    self.create_api_response = self.awsclient.create_rest_api(
  File "/root/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the CreateRestApi operation: The security token included in the request is invalid.

**Comment by DaveYesland** [comment]
What if you point it to `usr/lib/python3` or `/usr/lib/python3.7`?
