### ISSUE TITLE
Failed to load Bapp

### ISSUE THREAD

**Issue by 0xspade** [RhinoSecurityLabs/IPRotate_Burp_Extension#29]
Error Log

```
	at org.python.core.imp.importFrom(imp.java:1132)
	at socket$py.f$0(C:\Users\Spade\Documents\jython-standalone-2.7.0.jar\Lib\socket.py:132)
	at socket$py.call_function(C:\Users\Spade\Documents\jython-standalone-2.7.0.jar\Lib\socket.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.util.importer.importer_load_module(importer.java:109)
	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:163)
	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
	at org.python.core.imp.loadFromLoader(imp.java:587)
	at org.python.core.imp.find_module(imp.java:537)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_first(imp.java:870)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at botocore.session$py.f$0(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\botocore\session.py:1013)
	at botocore.session$py.call_function(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\botocore\session.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at boto3.session$py.f$0(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\boto3\session.py:28)
	at boto3.session$py.call_function(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\boto3\session.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at boto3$py.f$0(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\boto3\__init__.py:110)
	at boto3$py.call_function(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\BappModules\boto3\__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at org.python.pycode._pyx5.f$0(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\IPRotate.py:22)
	at org.python.pycode._pyx5.call_function(C:\Users\Spade\AppData\Roaming\BurpSuite\bapps\2eb2b1cb1cf34cc79cda36f0f9019874\IPRotate.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.dh0.<init>(Unknown Source)
	at burp.frl.a(Unknown Source)
	at burp.bmd.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: failed to create a child event loop
	at org.python.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
	at org.python.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at org.python.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
	at org.python.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
	... 121 more
Caused by: org.python.netty.channel.ChannelException: failed to open a new selector
	at org.python.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128)
	at org.python.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
	at org.python.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
	at org.python.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	... 130 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at java.base/sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:94)
	at java.base/sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171)
	at java.base/sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
	at java.base/java.nio.channels.Pipe.open(Pipe.java:155)
	at java.base/sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:142)
	at java.base/sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
	at org.python.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
	... 133 more
Caused by: java.net.BindException: Cannot assign requested address: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:503)
	at java.base/sun.nio.ch.Net.connect(Net.java:492)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:751)
	at java.base/java.nio.channels.SocketChannel.open(SocketChannel.java:194)
	at java.base/sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:127)
	at java.base/sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76)
	... 141 more
```

**Comment by DaveYesland** [comment]
How would you reproduce this error? Do you have boto3 installed and the correct Python modules directory set in your Burp Jython settings?

**Comment by phspade** [comment]
Hi,

>How would you reproduce this error?

Re-installing, and enabling the extension.

>Do you have boto3

I have installed boto3. btw, I have python3 in my system (windows)

>correct Python modules directory set in your Burp Jython settings

How do I know this if it's correct? 

This extension is working a few days before. after that, it's getting an error

**Comment by DaveYesland** [comment]
Did you ever figure this one out? I am not sure what is going on, but if it was working I am guessing it is something to do with your configuration.
