### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dipya004** [RhinoSecurityLabs/IPRotate_Burp_Extension#38]
Traceback (most recent call last):
  File "/home/dd/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 202, in enableGateway
    self.startAPIGateway()
  File "/home/dd/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 76, in startAPIGateway
    self.create_api_response = self.awsclient.create_rest_api(
  File "/home/dd/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/dd/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the CreateRestApi operation: Signature not yet current: 20210828T023040Z is still later than 20210827T193104Z (20210827T192604Z + 5 min.)

**Comment by DaveYesland** [comment]
This is likely because you system time is set incorrectly. Try running pool.ntp.org and making sure you system time is correct.
