### ISSUE TITLE
Connection was closed before we received a valid response from endpoint URL

### ISSUE THREAD

**Issue by testing22-0** [RhinoSecurityLabs/IPRotate_Burp_Extension#49]
I'm on Linux Mint 20.3 Cinnamon 5.2.7. 

I've followed all the steps with help from [this](https://www.youtube.com/watch?v=_YQLao6p9GM&t=440s) tutorial. I have both keys from AWS. I'm not using Burp proxy, also disabled VPN and firewall.

Here's the detailed log:
```
ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://apigateway.eu-west-3.amazonaws.com/restapis".
2022-12-21 00:15:28,594 botocore.retryhandler [DEBUG] Retry needed, action of: 6.67601483958
2022-12-21 00:15:28,595 botocore.endpoint [DEBUG] Response received to retry, sleeping for 6.67601483958 seconds
2022-12-21 00:15:35,278 botocore.hooks [DEBUG] Event request-created.api-gateway.CreateRestApi: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x153>>
2022-12-21 00:15:35,285 botocore.hooks [DEBUG] Event choose-signer.api-gateway.CreateRestApi: calling handler <function set_operation_specific_signer at 0x8a>
2022-12-21 00:15:35,296 botocore.auth [DEBUG] Calculating signature using v4 auth.
2022-12-21 00:15:35,298 botocore.auth [DEBUG] CanonicalRequest:
POST
/restapis

accept:application/json
host:apigateway.eu-west-3.amazonaws.com
x-amz-date:20221221T031535Z

accept;host;x-amz-date
4cfcac27cc9390d192123b6a135b54d6e763262a93f92bfe0bdf7a3b34132381
2022-12-21 00:15:35,299 botocore.auth [DEBUG] StringToSign:
AWS4-HMAC-SHA256
20221221T031535Z
20221221/eu-west-3/apigateway/aws4_request
8656b42c2cbaf8a632de5de4ca8bd25e1b725c2b616b7a88904d6213c0dd48e4
2022-12-21 00:15:35,302 botocore.auth [DEBUG] Signature:
1d56629db5fe28bc049121d86f667b49b7659f21a64b1b7e93969bcc582894fa
2022-12-21 00:15:35,303 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://apigateway.eu-west-3.amazonaws.com/restapis, headers={'Content-Length': '69', 'X-Amz-Date': '20221221T031535Z', 'Accept': 'application/json', 'Authorization': 'AWS4-HMAC-SHA256 Credential=**REDACTED**/20221221/eu-west-3/apigateway/aws4_request, SignedHeaders=accept;host;x-amz-date, Signature=1d56629db5fe28bc049121d86f667b49b7659f21a64b1b7e93969bcc582894fa', 'User-Agent': 'Boto3/1.9.225 Python/2.7.0 Java/17.0.2 Botocore/1.12.253'}>
2022-12-21 00:15:36,147 botocore.hooks [DEBUG] Event needs-retry.api-gateway.CreateRestApi: calling handler <botocore.retryhandler.RetryHandler object at 0x14e>
Traceback (most recent call last):
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 205, in enableGateway
    self.startAPIGateway()
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 79, in startAPIGateway
    self.create_api_response = self.awsclient.create_rest_api(
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 647, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/endpoint.py", line 228, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/home/juanb/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://apigateway.eu-west-3.amazonaws.com/restapis".
``` 

What can it be?

**Comment by DaveYesland** [comment]
Looks to be a network error? can you reach or ping apigateway.eu-west-3.amazonaws.com outside of Burp?

**Comment by DaveYesland** [comment]
Going to close this for now. Feel free to pull this repo again and try it again, there have been some updates.
