### ISSUE TITLE
ParamValidationError: Parameter validation failed:

### ISSUE THREAD

**Issue by MMquant** [RhinoSecurityLabs/IPRotate_Burp_Extension#7]
After successful plugin installation I'm getting following error after clicking "enable" button in "IP Rotate" tab:

```
Traceback (most recent call last):
  File "/root/Programs/IPRotate_Burp_Extension/IPRotate.py", line 167, in enableGateway
    self.startAPIGateway()
  File "/root/Programs/IPRotate_Burp_Extension/IPRotate.py", line 105, in startAPIGateway
    self.awsclient.put_integration(
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 585, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 640, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "connectionType", must be one of: restApiId, resourceId, httpMethod, type, integrationHttpMethod, uri, credentials, requestParameters, requestTemplates, passthroughBehavior, cacheNamespace, cacheKeyParameters, contentHandling

```

after this error the plugin remains disabled.

**Comment by DaveYesland** [comment]
Are you using valid AWS keys with permission to API Gateway?

**Comment by MMquant** [comment]
I have the user in group with following policies:
AmazonAPIGatewayInvokeFullAccess
AmazonAPIGatewayAdministrator

However even with those permissions I'm getting

```
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the PutMethod operation: User: arn:aws:iam::026972760124:user/Burp is not authorized to perform: apigateway:PUT on resource: arn:aws:apigateway:eu-west-3::/restapis/ms8vu1dxx1/resources/0jtfzj/methods/ANY
```

What are the correct policies?

**Comment by DaveYesland** [comment]
I am using AmazonAPIGatewayAdministrator with API Gateway full access and it works with no issues. Maybe there is something else going on with that account. Try spinning up just one gateway in a single region like us-east-1 and see if that works.

**Comment by DaveYesland** [comment]
Closing this for now since it is an issue with keys not the extension.

**Comment by MMquant** [comment]
The problem was outdated boto3 library. I fixed it with

`pip install boto3 -U`
